'use strict';
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-nav');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});
window.matchMedia('(min-width:821px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
const tabs=[...document.querySelectorAll('[data-preview]')];
function activateTab(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;document.getElementById('preview-'+t.dataset.preview).hidden=!active;});}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activateTab(tab));tab.addEventListener('keydown',e=>{let index;if(e.key==='ArrowRight')index=(i+1)%tabs.length;else if(e.key==='ArrowLeft')index=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else return;e.preventDefault();activateTab(tabs[index]);tabs[index].focus();});});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});let count=0;document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&button.dataset.filter!==card.dataset.category;if(!card.hidden)count++;});document.getElementById('feature-count').textContent=count+' capabilities'+(button.dataset.filter==='all'?' across your club':' · '+button.dataset.filter);}));
const formats={
knockout:['Single elimination','One loss ends the run. Winners advance through the bracket until a champion remains. Byes can accommodate uneven entry numbers.',['Quarter-finals','Quarter-finals','Quarter-finals','Quarter-finals'],['Semi-finals','Final → Champion']],
roundrobin:['Round robin','Everyone meets the other entrants in their group. Use single or double round robin to build standings over a series of fixtures.',['Team A vs B','Team A vs C','Team B vs C'],['Played · Won · Drawn','Group standings']],
double:['Double elimination','A second chance after the first defeat. Entrants move through winners’ and losers’ brackets, with elimination after two losses.',['Winners’ bracket','Losers’ bracket'],['Finalists','Grand final']],
swiss:['Swiss system','Play a chosen number of rounds without eliminating entrants after a loss. Pairings develop with results; pairing review may be required.',['Round 1','Round 2','Round 3'],['Results-based pairings','Final standings']],
multi:['Multistage','Combine two to eight stages. Choose formats, groups, rounds and qualifying places, then carry qualifiers into the next stage.',['Group A','Group B'],['Qualifiers','Knockout final']],
ladder:['Ladder / pyramid challenge','Members with current history and ranking can challenge one level up. The standard challenge day is the third Sunday of each month, unless the organiser changes it.',['Level 3 · Challengers','Level 2 · Contenders'],['Challenge one level up','Level 1 · Leader']],
league:['Multi-sport team league','Bring several sports into one team season. Define team counts, eligibility and points; optionally enable a virtual-credit auction.',['Registrations','Player cards & auction','Sport fixtures'],['Team lineups','Combined standings']]
};
const format=document.getElementById('format');
function renderFormat(){const [title,description,left,right]=formats[format.value];document.getElementById('format-title').textContent=title;document.getElementById('format-description').textContent=description;const board=document.getElementById('format-diagram');board.replaceChildren();const stages=document.createElement('div');stages.className='format-stages';[left,right].forEach(items=>{const col=document.createElement('div');col.className='format-stage';items.forEach(text=>{const row=document.createElement('span');row.textContent=text;col.append(row);});stages.append(col);});board.append(stages);}
if(format){renderFormat();format.addEventListener('change',renderFormat);}
const form=document.getElementById('club-brief');
if(form)form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d=new FormData(form);const content=['Hello AthleteOS,','We would like to explore AthleteOS for our club.','',...['club','name','email','members','hosting','priorities'].map(k=>k.toUpperCase()+': '+String(d.get(k)).trim()),'INTER-CLUB INTEREST: '+(d.has('federation')?'Yes':'Not selected')].join('\n');const url='mailto:contact@AthleteOS.club?subject='+encodeURIComponent('AthleteOS demo enquiry — '+String(d.get('club')).trim())+'&body='+encodeURIComponent(content);const status=document.getElementById('brief-status');status.replaceChildren(document.createTextNode('Your enquiry is ready. Open it in your email app, then review and send. '));const a=document.createElement('a');a.href=url;a.className='inline-link';a.textContent='Open email draft →';status.append(a);a.focus();});
